name: Deploy to GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to GCP Server
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Desplegar en servidor GCP
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 35.252.78.112
          username: luxuryhorizoncolombia
          key: ${{ secrets.GCP_SSH_KEY }}
          command_timeout: 30m
          script: |
            sudo git config --global --add safe.directory /home/luxuryhorizoncolombia/stock-alert-full-stack-app
            sudo GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git -C /home/luxuryhorizoncolombia/stock-alert-full-stack-app pull
            cd /home/luxuryhorizoncolombia/stock-alert-full-stack-app && sudo docker compose -f docker-compose.prod.yml up -d --build
