name: Deploy to GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to GCP Server
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Desplegar en servidor GCP
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 34.44.81.102
          username: ederbarrios
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            sudo git config --global --add safe.directory /home/ederb1_1c/stock-alerts
            sudo GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git -C /home/ederb1_1c/stock-alerts pull
            cd /home/ederb1_1c/stock-alerts && sudo docker compose up -d --build
